import Foundation

/// 运行时语言:跟随系统(默认)/ 中文 / English。菜单可切,即时生效。
/// (NSLocalizedString 只跟系统语言,不能运行时切,所以自建表。)
public enum Language {

    enum Choice: String { case system, zh, en }

    static var choice: Choice {
        get { Choice(rawValue: UserDefaults.standard.string(forKey: key) ?? "") ?? .system }
        set {
            UserDefaults.standard.set(newValue.rawValue, forKey: key)
        }
    }

    private static let key = "kingfisher.language"

    /// 实际生效语言:choice=system 时按设备首选语言(中文系→zh,否则 en)
    static var current: String {
        switch choice {
        case .zh: return "zh"
        case .en: return "en"
        case .system:
            let pref = Locale.preferredLanguages.first ?? "en"
            return pref.hasPrefix("zh") ? "zh" : "en"
        }
    }

    /// 取文案。查不到回退 key 本身(开发期易发现)。
    public static func t(_ key: String) -> String {
        let table = current == "zh" ? zh : en
        return table[key] ?? en[key] ?? key
    }

    private static let zh: [String: String] = [
        // 菜单
        "menu.callOver": "召唤过来",
        "menu.fish": "去抓条鱼",
        "menu.sing": "唱一个",
        "menu.feed": "喂条鱼",
        "growth.stage.stranger": "陌生",
        "growth.stage.acquainted": "相识",
        "growth.stage.familiar": "熟悉",
        "growth.stage.close": "亲近",
        "growth.stage.intimate": "亲密",
        "growth.stage.bonded": "缘定一生",
        "growth.hatchedSuffix": "(已孵化)",
        "growth.hatchCountSuffix": "(已孵化×%d)",
        "menu.perch": "停到窗口上",
        "menu.peck": "啄一下",
        "menu.toggleVisibility": "显示 / 隐藏",
        "menu.soundOn": "啾鸣声:开",
        "menu.soundOff": "啾鸣声:关",
        "menu.autoLogin": "开机自启",
        "menu.repairScreen": "修复屏幕",
        "menu.settings": "设置…",
        "menu.axUnauthorized": "⚠ 勿扰未生效:辅助功能未授权",
        "settings.lan": "局域网小鸟",
        "settings.lan.enable": "发现同一网络里的翡(对唱/串门/送鱼)",
        "settings.lan.note": "我的代号:%@(开启后广播代号与主题,不含 IP/主机名)。需同一路由器且未开「AP 隔离/客户端隔离」,公司或公共 WiFi 可能发现不到邻居。",
        "lan.none": "邻居:暂无(局域网)",
        "lan.online": "邻居:%@(在线)",
        "lan.visitMenu": "去邻居家串门",
        "lan.fishMenu": "给邻居送条鱼",
        "lan.pairTitle": "发现邻居:%@",
        "lan.pairBody": "同一网络里有另一只翡。允许它来串门、对唱和送鱼吗?\n(允许后可随时在设置里管理;拒绝则不再打扰)",
        "lan.allow": "允许",
        "lan.deny": "不再提示",
        "lan.dual": "邻居:%@(🤝双向已配对)",
        "lan.half": "邻居:%@(已允许,等对方确认)",
        "lan.found": "发现邻居:%@(设置里配对)",
        "lan.visitSent": "已去 %@ 家串门(对方屏幕见)",
        "lan.fishSent": "已给 %@ 送鱼(对方+亲密度)",
        "lan.visitCooldown": "串门冷却中(每对邻居 30 分钟一次)",
        "lan.needDual": "需对方也确认配对(现在是单向)",
        "lan.noPeer": "没有已配对的在线邻居",
        "lan.manage": "局域网邻居",
        "lan.visitFrom": "%@ 来串门了(它在你屏幕上)",
        "lan.fishFrom": "收到 %@ 送的鱼(亲密度+2)",
        "lan.visitCooldownLeft": "串门冷却中,还剩 %d 分钟",
        "lan.remove": "移除",
        "lan.denyBtn": "拒绝",
        "lan.undeny": "解除拒绝",
        "lan.offline": "(离线)",
        "lan.stateDual": "🤝双向已配对",
        "lan.stateHalf": "✅已允许·等对方确认",
        "lan.stateInbound": "🤝对方已允许你",
        "lan.stateUnknown": "❓未配对",
        "lan.stateDenied": "⛔已拒绝",
        "menu.checkUpdate": "检查更新…",
        "update.failed": "检查更新失败",
        "update.failedBody": "无法访问 GitHub(网络原因)。可手动前往 Releases 页面查看。",
        "update.openReleases": "打开 Releases 页",
        "update.latest": "已是最新版本",
        "update.found": "发现新版本",
        "update.downloadBody": "当前 v%@。前往下载?",
        "update.download": "前往下载",
        "update.install": "下载并更新",
        "update.later": "稍后",
        "update.checking": "检查中…",
        "update.checkingBody": "正在检查新版本…",
        "update.downloading": "正在下载更新",
        "update.ok": "好",
        "menu.about": "关于 翡",
        "menu.quit": "退出 翡",
        "menu.language": "语言",
        "menu.lang.system": "跟随系统",
        "menu.lang.zh": "中文",
        "menu.lang.en": "English",
        // 设置
        "settings.title": "翡 · 设置",
        "settings.theme": "主题",
        "settings.activity": "活跃度",
        "settings.speed": "动画速度",
        "settings.peck": "啄屏幕",
        "settings.sound": "啾鸣声",
        "settings.activity.low": "低",
        "settings.activity.mid": "中",
        "settings.activity.high": "高",
        // 天气联动(v1.5.0)
        "settings.weather": "天气联动",
        "settings.weather.enable": "启用天气联动",
        "settings.weather.note": "开启后将请求所选天气源查询天气(约 30 分钟一次);城市必填,留空默认北京;填短名(如 北京/顺义,勿带\"市/区\"后缀)。",
        "settings.weather.city": "城市",
        "settings.weather.cityPlaceholder": "如:北京 / 顺义;留空 = 北京",
        "settings.weather.provider": "数据源",
        "settings.weather.key": "和风 API Key",
        "settings.weather.host": "和风 API Host",
        "settings.weather.testKey": "测试",
        "settings.weather.testing": "状态:Key 测试中…",
        "settings.weather.keyOK": "状态:Key 有效(%@)",
        "settings.weather.keyBad": "状态:Key 无效(HTTP %d code %@)",
        "settings.weather.status": "状态:%@",
        "settings.weather.status.off": "未开启",
        "settings.weather.status.ok": "正常",
        "settings.weather.status.unavailable": "天气源不可用(已静默降级,不干预行为)",
        "weather.kind.sunny": "晴",
        "weather.kind.overcast": "阴",
        "weather.kind.rainLight": "小雨",
        "weather.kind.rainHeavy": "大雨",
        "weather.kind.thunder": "雷暴",
        "weather.kind.snowLight": "小雪",
        "weather.kind.snowHeavy": "大雪",
        "weather.kind.fog": "雾",
        "weather.kind.wind": "大风",
        "weather.kind.hot": "热",
        "weather.kind.cold": "冷",
        "weather.unavailable": "🌧 天气源不可用",
        "weather.alert.line": "⚠️ %@%@ · 鸟躲起来了",
        // 关于
        "about.title": "翡",
        "about.body": "一只住在你 Mac 上的小生灵。\n它会自己活动,也会回应你——\n至于它都会些什么,养着养着就知道了。\n\n点它、拖它,或者就让它待着。",
        "about.github": "GitHub 主页",
        "about.version": "当前版本 v%@",
        "about.ok": "好",
        // 无障碍/其他
        "ax.petName": "翡 · 翠鸟",
        "ax.petHelp": "点击它会害羞,拖动可移动。",
        "ax.tooltip": "翡 · 翠鸟桌面宠物",
        "statusitem.tooltip": "翡 · 翠鸟桌面宠物",
    ]

    private static let en: [String: String] = [
        // Menu
        "menu.callOver": "Call Over",
        "menu.fish": "Go Catch a Fish",
        "menu.sing": "Sing",
        "menu.feed": "Feed a Fish",
        "growth.stage.stranger": "Stranger",
        "growth.stage.acquainted": "Acquainted",
        "growth.stage.familiar": "Familiar",
        "growth.stage.close": "Close",
        "growth.stage.intimate": "Intimate",
        "growth.stage.bonded": "Bonded",
        "growth.hatchedSuffix": " (hatched)",
        "growth.hatchCountSuffix": " (hatched ×%d)",
        "menu.perch": "Perch on a Window",
        "menu.peck": "Peck",
        "menu.toggleVisibility": "Show / Hide",
        "menu.soundOn": "Chirp: On",
        "menu.soundOff": "Chirp: Off",
        "menu.autoLogin": "Launch at Login",
        "menu.repairScreen": "Repair Screen",
        "menu.settings": "Settings…",
        "menu.axUnauthorized": "⚠ Do Not Disturb inactive: Accessibility not granted",
        "settings.lan": "LAN Birds",
        "settings.lan.enable": "Discover other KingfisherPets on this network",
        "settings.lan.note": "My codename: %@ (broadcasts only codename + theme, never IP/hostname). Requires the same router without AP/client isolation — corporate or public Wi-Fi may not see neighbors.",
        "lan.none": "Neighbors: none (LAN)",
        "lan.online": "Neighbors: %@ (online)",
        "lan.visitMenu": "Visit a neighbor",
        "lan.fishMenu": "Send a fish to a neighbor",
        "lan.pairTitle": "Neighbor found: %@",
        "lan.pairBody": "Another KingfisherPet is on this network. Allow it to visit, sing duets and send fish?\n(You can manage this anytime in Settings; denying won't ask again.)",
        "lan.allow": "Allow",
        "lan.deny": "Don't ask again",
        "lan.dual": "Neighbors: %@ (mutual pair)",
        "lan.half": "Neighbors: %@ (awaiting their confirm)",
        "lan.found": "Neighbor found: %@ (pair in settings)",
        "lan.visitSent": "Visiting %@ (on their screen)",
        "lan.fishSent": "Fish sent to %@ (+bonding)",
        "lan.visitCooldown": "Visit cooldown (30 min per pair)",
        "lan.needDual": "Need mutual pairing first",
        "lan.noPeer": "No paired neighbor online",
        "lan.manage": "LAN Neighbors",
        "lan.visitFrom": "%@ is visiting your screen",
        "lan.fishFrom": "Fish from %@ (+2 bonding)",
        "lan.visitCooldownLeft": "Visit cooldown, %d min left",
        "lan.remove": "Remove",
        "lan.denyBtn": "Deny",
        "lan.undeny": "Undeny",
        "lan.offline": " (offline)",
        "lan.stateDual": "mutual pair",
        "lan.stateHalf": "allowed·awaiting",
        "lan.stateInbound": "they allowed you",
        "lan.stateUnknown": "unknown",
        "lan.stateDenied": "denied",
        "menu.checkUpdate": "Check for Updates…",
        "update.failed": "Update Check Failed",
        "update.failedBody": "Cannot reach GitHub. You can check the Releases page manually.",
        "update.openReleases": "Open Releases",
        "update.latest": "Up to Date",
        "update.found": "New Version",
        "update.downloadBody": "Current v%@. Download now?",
        "update.download": "Download",
        "update.install": "Download & Update",
        "update.later": "Later",
        "update.ok": "OK",
        "update.checking": "Checking…",
        "update.checkingBody": "Checking for updates…",
        "update.downloading": "Downloading Update",
        "menu.about": "About Fei",
        "menu.quit": "Quit Fei",
        "menu.language": "Language",
        "menu.lang.system": "Follow System",
        "menu.lang.zh": "中文",
        "menu.lang.en": "English",
        // Settings
        "settings.title": "Fei · Settings",
        "settings.theme": "Theme",
        "settings.activity": "Activity",
        "settings.speed": "Animation Speed",
        "settings.peck": "Peck the screen",
        "settings.sound": "Chirp",
        "settings.activity.low": "Low",
        "settings.activity.mid": "Med",
        "settings.activity.high": "High",
        // Weather (v1.5.0)
        "settings.weather": "Weather",
        "settings.weather.enable": "Enable weather",
        "settings.weather.note": "When on, the selected provider is queried every ~30 min; city is required and defaults to Beijing; use short names (no \"City/District\" suffix).",
        "settings.weather.city": "City",
        "settings.weather.cityPlaceholder": "e.g. Beijing / Shunyi; empty = Beijing",
        "settings.weather.provider": "Provider",
        "settings.weather.key": "QWeather API Key",
        "settings.weather.host": "QWeather API Host",
        "settings.weather.testKey": "Test",
        "settings.weather.testing": "Status: testing key…",
        "settings.weather.keyOK": "Status: key works (%@)",
        "settings.weather.keyBad": "Status: key rejected (HTTP %d code %@)",
        "settings.weather.status": "Status: %@",
        "settings.weather.status.off": "off",
        "settings.weather.status.ok": "ok",
        "settings.weather.status.unavailable": "unavailable (degraded silently)",
        "weather.kind.sunny": "Sunny",
        "weather.kind.overcast": "Overcast",
        "weather.kind.rainLight": "Light rain",
        "weather.kind.rainHeavy": "Heavy rain",
        "weather.kind.thunder": "Thunderstorm",
        "weather.kind.snowLight": "Light snow",
        "weather.kind.snowHeavy": "Heavy snow",
        "weather.kind.fog": "Fog",
        "weather.kind.wind": "Windy",
        "weather.kind.hot": "Hot",
        "weather.kind.cold": "Cold",
        "weather.unavailable": "🌧 Weather unavailable",
        "weather.alert.line": "⚠️ %@ %@ · hiding",
        // About
        "about.title": "Fei",
        "about.body": "A little creature living on your Mac.\nIt does its own thing, and answers to you—\nwhat it can do, you'll discover as you keep it around.\n\nClick it, drag it, or just let it be.",
        "about.github": "GitHub Page",
        "about.version": "Version v%@",
        "about.ok": "OK",
        // Accessibility
        "ax.petName": "Fei · Kingfisher",
        "ax.petHelp": "Click to make it shy; drag to move.",
        "ax.tooltip": "Fei · Kingfisher desktop pet",
        "statusitem.tooltip": "Fei · Kingfisher desktop pet",
    ]
}
