export declare function stageOf(intimacy: number): number;
export declare function affectionChance(stage: number): number;
export declare const STAGE_ZH: string[];
export declare const STAGE_EN: string[];
export declare function growthMenuTitle(intimacy: number, hatchCount: number, zh: boolean): string;
export declare const FEED_COOLDOWN_MS: number;
export declare function feedAllowed(nowMs: number, lastFeedAtMs: number | null): boolean;
export declare const FEED_GAIN: number;
export declare const PET_COOLDOWN_MS: number;
export declare function petAllowed(nowMs: number, lastPetAtMs: number | null): boolean;
export declare const DAILY_CAP: number;
export declare function capEffective(n: number, dayGain: number): number;
export declare const HATCH_RESET_TO: number;
